name-template: '${NEXT_MINOR_VERSION}'
tag-template: '${NEXT_MINOR_VERSION}'

categories:
  - title: '🚀 FEATURES'
    labels:
      - feature
      - enhancement
  - title: '🐛 FIXES'
    labels:
      - bug
      - fix
  - title: '🧰 MAINTENANCE'
    labels:
      - chore
      - cleanup

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## CHANGES

  $CHANGES