name: ⚠️ Bug report
description: Report any error or feature that produces an incorrect or unexpected result.
labels: [ "bug" ]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have used the search function to see if someone else has submitted the same bug report.
          required: true
        - label: I will describe the problem in as much detail as possible.
          required: true
  - type: input
    attributes:
      label: App version
      description: What application version do you use?
    validations:
      required: true
  - type: input
    attributes:
      label: Windows version
      description: What Windows version do you use?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '…'
        2. Click on '…'
        3. Scroll down to '…'
        4. etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you are experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Logs? Screenshots? Anything that will give us more context about the issue you are encountering!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
