name: "🚀 Feature Request"
description: "Suggest an idea or enhancement for this project."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea! We appreciate your feedback.
  - type: input
    id: app-version
    attributes:
      label: App Version
      description: "What version of Windows Memory Cleaner are you using? (e.g., 3.0.0)"
      placeholder: "X.X.X"
    validations:
      required: true
      pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  - type: textarea
    id: problem-description
    attributes:
      label: What problem are you trying to solve?
      description: A clear and concise description of the problem or limitation you are facing.
      placeholder: "e.g., I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: What is your suggested solution?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Any alternatives you've considered?
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context, mockups, or screenshots about the feature request here."
      placeholder: "You can drag and drop images here."
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues to make sure this feature has not been requested yet.
          required: true
        - label: This issue is focused on a single feature or enhancement.
          required: true
