name: Feature request
description: Suggest an idea for this project.
labels: [ "enhancement" ]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have used the search function to see if someone else has already submitted the same feature request.
          required: true
        - label: I will describe the problem in as much detail as possible.
          required: true
        - label: This issue only requests one feature, **not** multiple (related) features.
          required: true
  - type: input
    attributes:
      label: App version
      description: What application version do you use?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem you are trying to solve
      Description: Could you explain the problem you are trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe how you would like the app to help you solve that problem. Please be as specific as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots / Drawings / Technical details
      description: |
        If your request is about (or includes) changing or extending the user interface (UI), describe the UI and how the user would interact with it.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
