name: "Question"
description: "Ask a question about WinMemoryCleaner."
title: "<Your question here>"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! Please provide as much detail as possible so we can assist you.
  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Clearly describe your question or what you need help with.
      placeholder: e.g., "How do I enable clean on system startup?"
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App Version
      description: "What version of WinMemoryCleaner are you using? (See the About menu)"
      placeholder: e.g., 1.5.2
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Windows Version
      description: What version of Windows are you using?
      placeholder: e.g., Windows 10, Windows 11
    validations:
      required: false
  - type: textarea
    id: steps-tried
    attributes:
      label: Steps you've already tried
      description: Tell us what you've already tried to resolve your question.
      placeholder: e.g., "Checked the FAQ, restarted the app, etc."
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        _If your question is about a bug, please use the **Bug Report** template instead!_
