name: "🌐 Translation Request"
description: "Contribute a new translation or update an existing one."
labels: ["translation"]
body:
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: "What language are you contributing?"
      options:
        - "🌐 New Language"
        - "🇦🇱 Albanian"
        - "🇸🇦 Arabic"
        - "🇧🇬 Bulgarian"
        - "🇨🇳 Chinese (Simplified)"
        - "🇨🇳 Chinese (Traditional)"
        - "🇳🇱 Dutch"
        - "🇬🇧 English"
        - "🇫🇷 French"
        - "🇩🇪 German"
        - "🇬🇷 Greek"
        - "🇮🇱 Hebrew"
        - "🇭🇺 Hungarian"
        - "🇮🇩 Indonesian"
        - "🇮🇪 Irish"
        - "🇮🇹 Italian"
        - "🇯🇵 Japanese"
        - "🇰🇷 Korean"
        - "🇲🇰 Macedonian"
        - "🇳🇴 Norwegian"
        - "🇮🇷 Persian"
        - "🇵🇱 Polish"
        - "🇧🇷 Portuguese (BR)"
        - "🇵🇹 Portuguese (PT)"
        - "🇷🇺 Russian"
        - "🇷🇸 Serbian"
        - "🇸🇮 Slovenian"
        - "🇪🇸 Spanish"
        - "🇹🇭 Thai"
        - "🇹🇷 Turkish"
        - "🇺🇦 Ukrainian"
    validations:
      required: true
  - type: textarea
    id: json-file
    attributes:
      label: Translation JSON File
      description: |
        1.  **Use the source file as a reference:** **[English.json](https://github.com/IgorMundstein/WinMemoryCleaner/blob/main/src/Resources/Localization/English.json)**
        2.  **Follow the guidelines:** For detailed instructions, please see the **[Translation section in the README](https://github.com/IgorMundstein/WinMemoryCleaner?tab=readme-ov-file#-translation)**.
        3.  **Use neutral language:** Please provide neutral translations that avoid regional slang or cultural specifics.
        4.  **Attach your file:** You can either paste the content of your `.json` file below or attach the file by dragging it into this text box. If you are adding a new language, please also specify its name.
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have followed the translation guidelines in the README.md.
          required: true
        - label: I have tested my translation locally by creating a `{locale-description}.json` file.
          required: true
        - label: All translated text is in lowercase as requested (App automatically capitalizes the texts)
          required: true
