name: Analyze and Submit Dependencies

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**/*.sln'
      - 'src/**/*.csproj'
      - 'src/**/packages.config'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-submit:
    runs-on: windows-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('src/**/packages.config', 'src/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Restore dependencies and generate lock file
        run: nuget restore src/WinMemoryCleaner.sln -UseLockFile

      - name: Submit Dependency Graph
        uses: github/dependency-submission-action@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update dependencies [auto]"
          title: "Auto-update dependencies"
          body: "This pull request updates project dependencies."
          branch: "auto/dependency-update"
          delete-branch: true
