name: Build CSS

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Commit Tailwind CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Show npm config & possible .npmrc files
        run: |
          echo "--- Root directory listing ---"
          ls -al .
          echo "--- docs directory listing ---"
            ls -al docs || true
          echo "--- Root .npmrc ---"
          [ -f .npmrc ] && sed 's/^/ROOT .npmrc: /' .npmrc || echo "No root .npmrc"
          echo "--- docs/.npmrc ---"
          [ -f docs/.npmrc ] && sed 's/^/DOCS .npmrc: /' docs/.npmrc || echo "No docs/.npmrc"
          echo "--- npm config list (user + project) ---"
          npm config list

      - name: Clean npm cache (defensive)
        run: |
          npm cache clean --force
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 60000

      - name: Upgrade npm (optional)
        run: npm i -g npm@latest

      - name: Install dependencies (npm ci)
        working-directory: ./docs
        run: |
          echo "Running npm ci (expects package-lock.json to be in sync)..."
          npm ci --no-audit --no-fund

      - name: Build CSS
        working-directory: ./docs
        run: npm run build:css

      - name: Commit and push if changed
        run: |
          git add docs/assets/css/style.css docs/package-lock.json
          if ! git diff --cached --quiet; then
            git commit -m "chore(docs): build and commit new stylesheet"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Upload npm logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: /home/runner/.npm/_logs
