name: Build CSS

on:
  workflow_dispatch:

concurrency:
  group: build-css-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: read

env:
  DOCS_DIR: docs
  BUILD_CSS_PATH: docs/assets/css/style.css

jobs:
  build-css:
    name: Build CSS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Verify lock file
        run: |
          if [ ! -f "$DOCS_DIR/package-lock.json" ]; then
            echo "::error::Missing $DOCS_DIR/package-lock.json. Commit the lock file."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.DOCS_DIR }}/package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Prepare npm config
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config delete always-auth || true
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 60000

      - name: Compute source hash
        id: hash
        run: |
          set -euo pipefail
          FILE_LIST=$(mktemp)
          find "$DOCS_DIR" -type f \( \
            -name 'package.json' -o \
            -name 'package-lock.json' -o \
            -name 'tailwind.config.*' -o \
            -name 'postcss.config.*' -o \
            -path "$DOCS_DIR/src/*" -o \
            -path "$DOCS_DIR/assets/css/src/*" -o \
            -path "$DOCS_DIR/assets/css/tailwind/*" \
          \) 2>/dev/null | sort > "$FILE_LIST"
          if [ -s "$FILE_LIST" ]; then
            HASH_VALUE=$(xargs sha256sum < "$FILE_LIST" | sha256sum | cut -d' ' -f1)
          else
            HASH_VALUE="empty"
          fi
          echo "hash=$HASH_VALUE" >> "$GITHUB_OUTPUT"

      - name: Restore build cache
        id: build-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.BUILD_CSS_PATH }}
          key: build-css-${{ steps.hash.outputs.hash }}

      - name: Install dependencies
        working-directory: ${{ env.DOCS_DIR }}
        run: |
          set -euo pipefail
          npm ci --no-audit --no-fund

      - name: Skip build if cached
        id: maybe-skip
        if: steps.build-cache.outputs.cache-hit == 'true'
        run: |
          if [ -f "${BUILD_CSS_PATH}" ]; then
            echo "skip_build=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Build CSS
        if: steps.maybe-skip.outputs.skip_build != 'true'
        working-directory: ${{ env.DOCS_DIR }}
        run: |
          set -euo pipefail
          npm run build:css
          if [ ! -f "../${BUILD_CSS_PATH#"$DOCS_DIR/"}" ]; then
            echo "::error::Expected built CSS at ${BUILD_CSS_PATH} not found."
            exit 1
          fi

      - name: Validate deterministic build
        if: steps.maybe-skip.outputs.skip_build != 'true'
        run: |
          set -euo pipefail
          cp "${BUILD_CSS_PATH}" "${BUILD_CSS_PATH}.first"
          (cd "$DOCS_DIR" && npm run build:css)
          diff -q "${BUILD_CSS_PATH}.first" "${BUILD_CSS_PATH}" || echo "::warning::Non-deterministic build (CSS differs between consecutive runs)."

      - name: Commit CSS if changed
        if: steps.maybe-skip.outputs.skip_build != 'true'
        run: |
          set -euo pipefail
          if git diff --quiet -- "${BUILD_CSS_PATH}"; then
            exit 0
          fi
          git add "${BUILD_CSS_PATH}"
          git diff --cached --quiet && exit 0
          git commit -m "chore(docs): update built stylesheet"
          git push

      - name: Upload CSS artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: built-css
          path: ${{ env.BUILD_CSS_PATH }}
          if-no-files-found: warn
          retention-days: 7

      - name: Upload npm logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: /home/runner/.npm/_logs
