name: Submit to Chocolatey

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  submit-chocolatey:
    name: Submit to Chocolatey Community
    runs-on: windows-latest
    timeout-minutes: 30
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Get latest release tag
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            // Strip any 'v' prefix from the tag for cleaner versioning
            const tag = release.tag_name.startsWith('v') ? release.tag_name.substring(1) : release.tag_name;

            core.setOutput('tag', tag);
            console.log(`Latest release version: ${tag}`);
            return tag;

      - name: Set Release Version Environment Variable
        shell: powershell
        run: echo "RELEASE_TAG=${{ steps.get_release.outputs.tag }}" >> $env:GITHUB_ENV

      - name: Validate inputs and environment
        shell: powershell
        run: |
          if (-not ("${{ secrets.CHOCOLATEY_API_KEY }}")) {
            Write-Host "::error::CHOCOLATEY_API_KEY secret is not set!"
            exit 1
          }
          
          # Corrected regex to match Major.Minor.Patch (e.g., 1.0.0)
          if (-not ("$env:RELEASE_TAG" -match "^[0-9]+\.[0-9]+\.[0-9]+$")) {
            Write-Host "::error::Version format must be Major.Minor.Patch (e.g., 1.0.0, 1.1.2, 2.8.3). Found: $env:RELEASE_TAG"
            exit 1
          }

      - name: Check if version already exists on Chocolatey
        id: check_chocolatey
        shell: powershell
        run: |
          Write-Host "::group::Checking existing versions on Chocolatey"
          
          try {
            $response = Invoke-RestMethod -Uri "https://community.chocolatey.org/api/v2/Packages()?`$filter=Id%20eq%20'winmemorycleaner'" -Method Get
            $existingVersions = $response.entry.properties.Version.'#text'
            
            if ($existingVersions -contains "$env:RELEASE_TAG") {
              Write-Host "::notice::Version $env:RELEASE_TAG already exists on Chocolatey. Skipping submission."
              echo "skip=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            } else {
              Write-Host "::notice::Version $env:RELEASE_TAG not found, proceeding with submission."
              echo "skip=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
            }
          }
          catch {
            Write-Host "::notice::Could not check existing versions, proceeding with submission just in case."
            echo "skip=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }
          
          Write-Host "::endgroup::"

      - name: Verify release assets
        if: steps.check_chocolatey.outputs.skip == 'false'
        shell: powershell
        run: |
          Write-Host "::group::Verifying release assets"
          
          $releaseUrl = "https://api.github.com/repos/${{ github.repository }}/releases/tags/v$env:RELEASE_TAG"
          
          try {
            $release = Invoke-RestMethod -Uri $releaseUrl -Method Get
            $assets = $release.assets | Where-Object { $_.name -eq "WinMemoryCleaner.exe" }
            
            if (-not $assets) {
              Write-Host "::error::WinMemoryCleaner.exe not found in release assets"
              exit 1
            }
            
            Write-Host "::notice::Release verification successful"
          }
          catch {
            Write-Host "::error::Release v$env:RELEASE_TAG not found"
            exit 1
          }
          
          Write-Host "::endgroup::"

      - name: Download and verify release asset
        if: steps.check_chocolatey.outputs.skip == 'false'
        shell: powershell
        run: |
          Write-Host "::group::Downloading release asset"
          
          $downloadUrl = "https://github.com/${{ github.repository }}/releases/download/v$env:RELEASE_TAG/WinMemoryCleaner.exe"
          $outputFile = "WinMemoryCleaner.exe"
          
          Invoke-WebRequest -Uri $downloadUrl -OutFile $outputFile -UseBasicParsing
          
          if (!(Test-Path $outputFile) -or (Get-Item $outputFile).Length -lt 10000) {
            Write-Host "::error::Downloaded file is missing or too small."
            exit 1
          }
          
          Write-Host "::notice::Downloaded WinMemoryCleaner.exe"
          Write-Host "::endgroup::"

      - name: Calculate and verify SHA256
        if: steps.check_chocolatey.outputs.skip == 'false'
        id: sha
        shell: powershell
        run: |
          $hash = Get-FileHash -Path "WinMemoryCleaner.exe" -Algorithm SHA256
          $sha256 = $hash.Hash.ToLower()
          
          echo "SHA256=$sha256" >> $env:GITHUB_ENV
          echo "sha256=$sha256" >> $env:GITHUB_OUTPUT
          Write-Host "::notice::SHA256: $sha256"

      - name: Fetch repository metadata
        if: steps.check_chocolatey.outputs.skip == 'false'
        id: metadata
        uses: actions/github-script@v7
        with:
          script: |
            const { data: repo } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('desc', repo.description?.trim() || 'No description found.');
            core.setOutput('homepage', repo.homepage || repo.html_url);

      - name: Install Chocolatey and dependencies
        if: steps.check_chocolatey.outputs.skip == 'false'
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          refreshenv

      - name: Generate Chocolatey package files
        if: steps.check_chocolatey.outputs.skip == 'false'
        shell: powershell
        run: |
          $packageDir = "chocolatey-package"
          New-Item -ItemType Directory -Path $packageDir -Force
          $toolsDir = Join-Path $packageDir "tools"
          New-Item -ItemType Directory -Path $toolsDir -Force

          $nuspecContent = @"
          <?xml version="1.0" encoding="utf-8"?>
          <package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
            <metadata>
              <id>winmemorycleaner</id>
              <version>$env:RELEASE_TAG</version>
              <owners>Igor Mundstein</owners>
              <title>Windows Memory Cleaner</title>
              <authors>Igor Mundstein</authors>
              <projectUrl>${{ steps.metadata.outputs.homepage }}</projectUrl>
              <packageSourceUrl>https://github.com/${{ github.repository }}</packageSourceUrl>
              <releaseNotes>https://github.com/${{ github.repository }}/releases/tag/v$env:RELEASE_TAG</releaseNotes>
              <licenseUrl>https://github.com/${{ github.repository }}/blob/main/LICENSE</licenseUrl>
              <bugTrackerUrl>https://github.com/${{ github.repository }}/issues</bugTrackerUrl>
              <tags>memory cleaner ram optimization windows portable</tags>
              <summary>${{ steps.metadata.outputs.desc }}</summary>
              <description>${{ steps.metadata.outputs.desc }}</description>
            </metadata>
            <files>
              <file src="tools\**" target="tools" />
            </files>
          </package>
          "@
          $nuspecContent | Out-File -FilePath (Join-Path $packageDir "winmemorycleaner.nuspec") -Encoding UTF8

          $installScript = @"
          `$ErrorActionPreference = 'Stop'
          `$toolsDir = "`$(Split-Path -parent `$MyInvocation.MyCommand.Definition)"
          `$packageArgs = @{
            packageName    = 'winmemorycleaner'
            fileType       = 'EXE'
            url64bit       = 'https://github.com/${{ github.repository }}/releases/download/v$env:RELEASE_TAG/WinMemoryCleaner.exe'
            checksum64     = '$env:SHA256'
            checksumType64 = 'sha256'
          }
          Install-ChocolateyPackage @packageArgs
          "@
          $installScript | Out-File -FilePath (Join-Path $toolsDir "chocolateyinstall.ps1") -Encoding UTF8
          
          $uninstallScript = @"
          `$ErrorActionPreference = 'Continue'
          Uninstall-ChocolateyPackage 'winmemorycleaner'
          "@
          $uninstallScript | Out-File -FilePath (Join-Path $toolsDir "chocolateyuninstall.ps1") -Encoding UTF8

      - name: Build and Push Chocolatey package
        if: steps.check_chocolatey.outputs.skip == 'false'
        shell: powershell
        run: |
          cd chocolatey-package
          choco pack
          
          $nupkgFile = Get-ChildItem -Filter "*.nupkg" | Select-Object -First 1
          if (-not $nupkgFile) {
            Write-Host "::error::No .nupkg file was created"
            exit 1
          }

          choco apikey --key "${{ secrets.CHOCOLATEY_API_KEY }}" --source https://push.chocolatey.org/
          choco push `$nupkgFile.FullName --source https://push.chocolatey.org/
          
          if (`$LASTEXITCODE -ne 0) {
            Write-Host "::error::Failed to push package to Chocolatey"
            exit 1
          }
          Write-Host "::notice::Package successfully submitted."

      - name: Cleanup
        if: always()
        shell: powershell
        run: |
          Remove-Item -Path "WinMemoryCleaner.exe" -ErrorAction SilentlyContinue
          Remove-Item -Path "chocolatey-package" -Recurse -ErrorAction SilentlyContinue
          Write-Host "::notice::Cleanup completed"
