name: Submit to Hybrid Analysis

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  submit-and-analyze:
    name: Submit Latest Release to Hybrid Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Get Latest Release Info
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const asset = release.assets.find(asset => asset.name.endsWith('.exe'));
            if (!asset) {
              core.setFailed('Could not find .exe asset in the latest release.');
              return;
            }
            core.setOutput('asset_url', asset.browser_download_url);
            core.setOutput('asset_name', asset.name);
            core.setOutput('release_tag', release.tag_name);

      - name: Download Release Asset
        run: |
          echo "Downloading ${{ steps.get_release.outputs.asset_name }} from release ${{ steps.get_release.outputs.release_tag }}"
          curl -fL --retry 5 --retry-delay 5 \
            -o "${{ steps.get_release.outputs.asset_name }}" \
            "${{ steps.get_release.outputs.asset_url }}"

      - name: Submit to Hybrid Analysis and Get Report
        id: ha_analysis
        uses: bluecatengineering/hybrid-analysis-action@v1
        with:
          api_key: ${{ secrets.HYBRID_ANALYSIS_API_KEY }}
          file: ${{ steps.get_release.outputs.asset_name }}
          environment_id: '100' # Windows 7 64-bit

      - name: Display Analysis Summary
        run: |
          echo "## Hybrid Analysis Report Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Verdict:** ${{ steps.ha_analysis.outputs.verdict }}" >> $GITHUB_STEP_SUMMARY
          echo "- **AV Detections:** ${{ steps.ha_analysis.outputs.av_detect }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Malicious:** ${{ steps.ha_analysis.outputs.malicious }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Suspicious:** ${{ steps.ha_analysis.outputs.suspicious }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Report URL:** https://hybrid-analysis.com/sample/${{ steps.ha_analysis.outputs.sha256 }}" >> $GITHUB_STEP_SUMMARY

      - name: Check Verdict
        if: steps.ha_analysis.outputs.verdict != 'no-specific-threat'
        run: |
          echo "::error::Hybrid Analysis returned a non-clean verdict: ${{ steps.ha_analysis.outputs.verdict }}"
          exit 1
