name: 'Update CHANGELOG.md from Release Notes'

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  changelog-from-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all releases and generate CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/releases \
            --paginate \
            --jq '.[] | "## \(.name // .tag_name)\n\n\(.body // "No release notes provided.")\n---\n"' > CHANGELOG.md

      - name: Commit and push CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update changelog from release notes'
          file_pattern: CHANGELOG.md
