name: 'Update CHANGELOG'

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-and-merge-pr:
    name: 'Create and Auto-Merge Changelog PR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Generate Changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/releases \
            --paginate \
            --jq '.[] | "## \(.name // .tag_name)\n\n\(.body // "No release notes provided.")\n---\n"' > CHANGELOG.md

      - name: 'Create Pull Request'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          commit-message: 'docs: update changelog from release notes'
          title: 'Docs: Update CHANGELOG.md'
          body: 'This is an automated PR updating the CHANGELOG.md from release notes.'
          branch: 'changelog/update-${{ github.run_id }}'
          delete-branch: true

      - name: 'Approve the PR'
        if: steps.cpr.outputs.pull-request-number != ''
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: 'Enable Auto-Merge'
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
