name: 'Update CHANGELOG'

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          ref: main

      - name: Generate Changelog
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/releases \
            --paginate \
            --jq '.[] | "## \(.name // .tag_name)\n\n**\(.published_at | split(\"T\")[0])**\n\n---\n\n\(.body // \"No release notes provided.\")\n"' |
            sed -E 's/!\[[^]]*\]\([^)]+\)//g' | \
            sed -E 's/<img[^>]+>//g' | \
            awk '
              /^## / { if (NR != 1) print ""; print; next }
              /^\*\*/ { print; next }
              /^---$/ {
                if (prev != "") print ""
                print "---"
                getline nextline
                if (nextline != "") print ""
                print nextline
                next
              }
              { print }
              { prev = $0 }
            ' > CHANGELOG.md

      - name: Force push CHANGELOG.md to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog from release notes" || echo "No changes to commit"
          git push origin HEAD:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
