name: Submit to Scoop

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: submit-to-scoop-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

env:
  UPSTREAM_REPO: ScoopInstaller/Main
  UPSTREAM_BRANCH: master
  FORK_REPO: ${{ github.repository_owner }}/Scoop
  APP_NAME: WinMemoryCleaner
  MANIFEST_NAME: winmemorycleaner
  LICENSE_ID: GPL-3.0-or-later
  ASSET_FILE: WinMemoryCleaner.zip
  PAT_NAME: PAT_TOKEN

jobs:
  submit:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve version
        id: version
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ("${{ github.event_name }}" -eq "release") {
            $tag = "${{ github.event.release.tag_name }}"
          } else {
            $latest = gh release list --limit 1 | Select-Object -First 1
            if (-not $latest) { Write-Error "No releases found."; exit 1 }
            $tag = ($latest -split '\s+')[0]
          }
          if ([string]::IsNullOrWhiteSpace($tag)) { Write-Error "Tag empty"; exit 1 }
          "tag=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "version=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "Version: $tag"

      - name: Check upstream (skip if identical)
        id: upstream
        shell: pwsh
        run: |
          $url = "https://raw.githubusercontent.com/${{ env.UPSTREAM_REPO }}/${{ env.UPSTREAM_BRANCH }}/bucket/${{ env.MANIFEST_NAME }}.json"
          try {
            $data = Invoke-RestMethod -Uri $url -Method Get -TimeoutSec 15 -ErrorAction Stop
            if ($data.version -eq "${{ steps.version.outputs.version }}") {
              "skip=yes" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              Write-Host "Upstream already at this version."
            } else {
              "skip=no" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              Write-Host "Upstream has different version ($($data.version)); will update."
            }
          } catch {
            "skip=no" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            Write-Host "Manifest not present upstream; new submission."
          }

      - name: Stop (already current)
        if: steps.upstream.outputs.skip == 'yes'
        run: echo "Nothing to do."

      - name: Get repo metadata
        if: steps.upstream.outputs.skip == 'no'
        id: meta
        uses: actions/github-script@v7
        with:
          script: |
            const { data: repo } = await github.rest.repos.get({ owner: context.repo.owner, repo: context.repo.repo });
            const fallback = 'Portable RAM cleaner that uses native Windows features to optimize memory.';
            let desc = (repo.description || '').trim();
            if (!desc) desc = fallback;
            // keep neutral & concise
            desc = desc.replace(/\b(free|smart|compact|advanced|powerful|lightweight)\b/gi,'').replace(/\s{2,}/g,' ').trim();
            if (!desc) desc = fallback;
            core.setOutput('desc', desc);
            core.setOutput('homepage', repo.homepage || repo.html_url);
            core.setOutput('license', process.env.LICENSE_ID);

      - name: Probe asset (fast)
        if: steps.upstream.outputs.skip == 'no'
        id: asset
        shell: pwsh
        run: |
          $url = "https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/${{ env.ASSET_FILE }}"
          try {
            $r = Invoke-WebRequest -Uri $url -Method Head -UseBasicParsing -TimeoutSec 15 -ErrorAction Stop
            if ($r.StatusCode -lt 200 -or $r.StatusCode -ge 400) { throw "Status $($r.StatusCode)" }
          } catch {
            Write-Error "Asset not reachable at $url"
            exit 1
          }
          "asset_url=$url" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "Asset OK"

      - name: Download & hash
        if: steps.upstream.outputs.skip == 'no'
        id: hash
        shell: pwsh
        run: |
          $url = "${{ steps.asset.outputs.asset_url }}"
          $file = "${{ env.ASSET_FILE }}"
          Invoke-WebRequest -Uri $url -OutFile $file -UseBasicParsing -ErrorAction Stop -TimeoutSec 120
          if ((Get-Item $file).Length -le 0) { Write-Error "Empty file"; exit 1 }
          $sha = (Get-FileHash -Path $file -Algorithm SHA256).Hash.ToLower()
          "sha256=$sha" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "SHA256: $sha"

      - name: Generate manifest
        if: steps.upstream.outputs.skip == 'no'
        id: manifest
        shell: pwsh
        run: |
          $version  = "${{ steps.version.outputs.version }}"
          $tag      = "${{ steps.version.outputs.tag }}"
          $desc     = "${{ steps.meta.outputs.desc }}"
          $homepage = "${{ steps.meta.outputs.homepage }}"
          $license  = "${{ steps.meta.outputs.license }}"
          $hash     = "${{ steps.hash.outputs.sha256 }}"
          $owner    = "${{ github.repository_owner }}"
          $repo     = "${{ github.event.repository.name }}"
          if (-not $repo) { $repo = ("${{ github.repository }}" -split "/")[1] }

          $obj = [ordered]@{
            version     = $version
            description = $desc
            homepage    = $homepage
            license     = $license
            url         = "https://github.com/$owner/$repo/releases/download/$tag/${{ env.ASSET_FILE }}"
            hash        = $hash
            bin         = "${{ env.APP_NAME }}.exe"
            shortcuts   = @(@("${{ env.APP_NAME }}.exe","${{ env.APP_NAME }}"))
            checkver    = @{ github = "$owner/$repo" }
            autoupdate  = @{ url = "https://github.com/$owner/$repo/releases/download/`$version/${{ env.ASSET_FILE }}" }
          }

          New-Item -Type Directory -Force -Path manifest-out | Out-Null
          $path = "manifest-out/${{ env.MANIFEST_NAME }}.json"
          ($obj | ConvertTo-Json -Depth 5 | Out-String).Trim() | Set-Content -LiteralPath $path -Encoding UTF8
          "path=$path" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Get-Content $path

      - name: Critical validation
        if: steps.upstream.outputs.skip == 'no'
        shell: pwsh
        run: |
          $p = "${{ steps.manifest.outputs.path }}"
          $j = Get-Content $p -Raw | ConvertFrom-Json
          $ok = $true
          foreach ($f in 'version','url','hash','bin','autoupdate','checkver') {
            if (-not $j.PSObject.Properties.Name.Contains($f)) { Write-Host "Missing $f"; $ok=$false }
          }
          if (-not $j.autoupdate.url.Contains('$version')) { Write-Host "autoupdate missing \$version"; $ok=$false }
          if ($j.shortcuts.Count -lt 1 -or $j.shortcuts[0].Count -ne 2) { Write-Host "Bad shortcuts"; $ok=$false }
          if (-not $ok) { Write-Error "Critical validation failed"; exit 1 }
          Write-Host "Critical validation passed."

      - name: Compose PR body
        if: steps.upstream.outputs.skip == 'no'
        id: prbody
        shell: pwsh
        run: |
          $isUpdate = if ("${{ steps.upstream.outputs.skip }}" -eq 'no' -and "${{ steps.upstream.outputs.update }}" -eq 'yes') { 'yes' } else { 'no' }
          $version = "${{ steps.version.outputs.version }}"
          $tag = "${{ steps.version.outputs.tag }}"
          $homepage = "${{ steps.meta.outputs.homepage }}"
          $description = "${{ steps.meta.outputs.desc }}"
          $action = if ($isUpdate -eq 'yes') { 'Update to' } else { 'Add version' }
          $title = "${{ env.MANIFEST_NAME }}: $action $version"

          $body = @(
            "$(if ($isUpdate -eq 'yes') {'Updates the manifest for'} else {'Adds the initial manifest for'}) ${{ env.APP_NAME }} version $version."
            ""
            "> $description"
            ""
            "- **Project Homepage:** $homepage"
            "- **Release Notes:** https://github.com/${{ github.repository }}/releases/tag/$tag"
            ""
            "Checklist:"
            "- hash ok"
            "- autoupdate placeholder ok"
            "- shortcuts schema ok"
          ) -join "`n"

          Set-Content pr_body.txt -Value $body -Encoding UTF8
          "file=pr_body.txt" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "title=$title" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create PR
        if: steps.upstream.outputs.skip == 'no'
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets[PAT_NAME] }}
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          $version = "${{ steps.version.outputs.version }}"
          $branch  = "update/${{ env.MANIFEST_NAME }}-$version"
          git clone "https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ env.FORK_REPO }}.git" fork --depth=1
          Set-Location fork
          git remote add upstream "https://github.com/${{ env.UPSTREAM_REPO }}.git"
          git fetch upstream "${{ env.UPSTREAM_BRANCH }}" --depth=1
          if (git ls-remote --heads origin $branch) { git push origin :$branch }
          git checkout -b $branch "upstream/${{ env.UPSTREAM_BRANCH }}"
          Copy-Item "../${{ steps.manifest.outputs.path }}" "bucket/${{ env.MANIFEST_NAME }}.json" -Force
          git add "bucket/${{ env.MANIFEST_NAME }}.json"
          $commit = "${{ env.MANIFEST_NAME }}: $( if ('${{ steps.upstream.outputs.update }}' -eq 'yes') { 'Update to' } else { 'Add version' } ) $version"
          git commit -m $commit
          git push origin $branch
          $title = "${{ steps.prbody.outputs.title }}"
          $bodyFile = "../${{ steps.prbody.outputs.file }}"
          $out = gh pr create --repo "${{ env.UPSTREAM_REPO }}" --head "${{ github.repository_owner }}:$branch" --base "${{ env.UPSTREAM_BRANCH }}" --title "$title" --body-file "$bodyFile" 2>&1
          if ($LASTEXITCODE -ne 0 -and $out -notmatch 'already exists') {
            Write-Host $out
            exit 1
          }
          Write-Host "PR done."
