name: Submit to Scoop

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: submit-to-scoop-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

env:
  UPSTREAM_REPO: ScoopInstaller/Main
  UPSTREAM_BRANCH: master
  FORK_REPO: ${{ github.repository_owner }}/Scoop
  APP_NAME: WinMemoryCleaner
  MANIFEST_NAME: winmemorycleaner
  LICENSE_ID: GPL-3.0-or-later
  ASSET_FILE: WinMemoryCleaner.zip
  FIXED_DESCRIPTION: Portable RAM cleaner using native Windows features to optimize memory.

jobs:
  submit:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve version
        id: version
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ("${{ github.event_name }}" -eq "release") {
            $tag = "${{ github.event.release.tag_name }}"
          } else {
            $latest = gh release list --limit 1 | Select-Object -First 1
            if (-not $latest) { Write-Error "No releases found."; exit 1 }
            $tag = ($latest -split '\s+')[0]
          }
          if ([string]::IsNullOrWhiteSpace($tag)) { Write-Error "Tag empty"; exit 1 }
          "tag=$tag"     | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "version=$tag" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "Version: $tag"

      - name: Check existing upstream PR (avoid duplicate)
        id: existing_pr
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $branch = "update/${{ env.MANIFEST_NAME }}-${{ steps.version.outputs.version }}"
          # Query upstream for open PRs with head = yourfork:branch
          $encodedHead = [System.Uri]::EscapeDataString("${{ github.repository_owner }}:$branch")
          $url = "https://api.github.com/repos/${{ env.UPSTREAM_REPO }}/pulls?state=open&head=$encodedHead"
          try {
            $resp = gh api -H "Accept: application/vnd.github+json" $url 2>$null | ConvertFrom-Json
          } catch {
            $resp = @()
          }
          if ($resp -and $resp.Count -gt 0) {
            "pr_exists=yes" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            Write-Host "An open upstream PR for branch '$branch' already exists: $($resp[0].html_url)"
          } else {
            "pr_exists=no" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            Write-Host "No existing upstream PR for branch '$branch'."
          }
          "branch=$branch" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Check upstream (skip if identical)
        if: steps.existing_pr.outputs.pr_exists == 'no'
        id: upstream
        shell: pwsh
        run: |
          $url = "https://raw.githubusercontent.com/${{ env.UPSTREAM_REPO }}/${{ env.UPSTREAM_BRANCH }}/bucket/${{ env.MANIFEST_NAME }}.json"
          try {
            $data = Invoke-RestMethod -Uri $url -Method Get -TimeoutSec 15 -ErrorAction Stop
            if ($data.version -eq "${{ steps.version.outputs.version }}") {
              "skip=yes"   | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              "update=yes" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              Write-Host "Upstream already at this version."
            } else {
              "skip=no"    | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              "update=yes" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              Write-Host "Upstream has version $($data.version); will update."
            }
          } catch {
            "skip=no"   | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "update=no" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            Write-Host "Manifest not present upstream; new submission."
          }

      - name: Stop (duplicate PR already open)
        if: steps.existing_pr.outputs.pr_exists == 'yes'
        run: echo "Duplicate upstream PR already exists. Exiting early."

      - name: Stop (already current upstream)
        if: steps.existing_pr.outputs.pr_exists == 'no' && steps.upstream.outputs.skip == 'yes'
        run: echo "Nothing to do (upstream already current)."

      - name: Probe asset
        if: steps.existing_pr.outputs.pr_exists == 'no' && steps.upstream.outputs.skip == 'no'
        id: asset
        shell: pwsh
        run: |
          $url = "https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/${{ env.ASSET_FILE }}"
          try {
            $r = Invoke-WebRequest -Uri $url -Method Head -UseBasicParsing -TimeoutSec 15 -ErrorAction Stop
            if ($r.StatusCode -lt 200 -or $r.StatusCode -ge 400) { throw "Status $($r.StatusCode)" }
          } catch {
            Write-Error "Asset not reachable at $url"
            exit 1
          }
            "asset_url=$url" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "Asset OK"

      - name: Download & hash
        if: steps.existing_pr.outputs.pr_exists == 'no' && steps.upstream.outputs.skip == 'no'
        id: hash
        shell: pwsh
        run: |
          $url = "${{ steps.asset.outputs.asset_url }}"
          $file = "${{ env.ASSET_FILE }}"
          Invoke-WebRequest -Uri $url -OutFile $file -UseBasicParsing -ErrorAction Stop -TimeoutSec 120
          if ((Get-Item $file).Length -le 0) { Write-Error "Empty file"; exit 1 }
          $sha = (Get-FileHash -Path $file -Algorithm SHA256).Hash.ToLower()
          "sha256=$sha" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "SHA256: $sha"

      - name: Generate manifest
        if: steps.existing_pr.outputs.pr_exists == 'no' && steps.upstream.outputs.skip == 'no'
        id: manifest
        shell: pwsh
        run: |
          $version = "${{ steps.version.outputs.version }}"
          $tag     = "${{ steps.version.outputs.tag }}"
          $hash    = "${{ steps.hash.outputs.sha256 }}"
          $owner   = "${{ github.repository_owner }}"
          $repo    = "${{ github.event.repository.name }}"
          if (-not $repo) { $repo = ("${{ github.repository }}" -split "/")[1] }

          $obj = [ordered]@{
            version     = $version
            description = "${{ env.FIXED_DESCRIPTION }}"
            homepage    = "https://github.com/$owner/$repo"
            license     = "${{ env.LICENSE_ID }}"
            url         = "https://github.com/$owner/$repo/releases/download/$tag/${{ env.ASSET_FILE }}"
            hash        = $hash
            bin         = "${{ env.APP_NAME }}.exe"
            shortcuts   = @(@("${{ env.APP_NAME }}.exe","${{ env.APP_NAME }}"))
            checkver    = "github"
            autoupdate  = @{ url = "https://github.com/$owner/$repo/releases/download/`$version/${{ env.ASSET_FILE }}" }
          }

          New-Item -Type Directory -Force -Path manifest-out | Out-Null
          $path = "manifest-out/${{ env.MANIFEST_NAME }}.json"
          ($obj | ConvertTo-Json -Depth 5 | Out-String).Trim() | Set-Content -LiteralPath $path -Encoding UTF8
          "path=$path" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Get-Content $path

      - name: Critical validation
        if: steps.existing_pr.outputs.pr_exists == 'no' && steps.upstream.outputs.skip == 'no'
        shell: pwsh
        run: |
          $p = "${{ steps.manifest.outputs.path }}"
          $raw = Get-Content $p -Raw
          $j = $raw | ConvertFrom-Json
          $ok = $true
          foreach ($f in 'version','url','hash','bin','autoupdate','checkver','shortcuts') {
            if (-not $j.PSObject.Properties.Name.Contains($f)) { Write-Host "Missing $f"; $ok=$false }
          }
          if (-not $j.autoupdate.url.Contains('$version')) { Write-Host "autoupdate missing \$version"; $ok=$false }
          if ($j.shortcuts.Count -lt 1 -or $j.shortcuts[0].Count -ne 2) { Write-Host "Shortcuts malformed"; $ok=$false }
          if ($j.checkver -ne 'github') { Write-Host "checkver not 'github' shorthand"; $ok=$false }
          if (-not $ok) {
            Write-Host "Manifest content:"
            Write-Host $raw
            Write-Error "Critical validation failed"
            exit 1
          }
          Write-Host "Validation OK."

      - name: Compose PR body
        if: steps.existing_pr.outputs.pr_exists == 'no' && steps.upstream.outputs.skip == 'no'
        id: prbody
        shell: pwsh
        run: |
          $isUpdate = "${{ steps.upstream.outputs.update }}"
          $version  = "${{ steps.version.outputs.version }}"
          $tag      = "${{ steps.version.outputs.tag }}"
          $desc     = "${{ env.FIXED_DESCRIPTION }}"
          $action   = if ($isUpdate -eq 'yes') { 'Update to' } else { 'Add version' }
          $title    = "${{ env.MANIFEST_NAME }}: $action $version"
          $body = @(
            "$(if ($isUpdate -eq 'yes') {'Updates the manifest for'} else {'Adds the initial manifest for'}) ${{ env.APP_NAME }} version $version."
            ""
            "> $desc"
            ""
            "- **Project Homepage:** https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}"
            "- **Release Notes:** https://github.com/${{ github.repository }}/releases/tag/$tag"
            ""
            "Checklist:"
            "- hash ok"
            "- checkver github shorthand ok"
            "- autoupdate placeholder ok"
            "- shortcuts schema ok"
          ) -join "`n"
          Set-Content pr_body.txt -Value $body -Encoding UTF8
          "file=pr_body.txt" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "title=$title" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create PR
        if: steps.existing_pr.outputs.pr_exists == 'no' && steps.upstream.outputs.skip == 'no'
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          $branch  = "${{ steps.existing_pr.outputs.branch }}"
          $version = "${{ steps.version.outputs.version }}"
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone "https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ env.FORK_REPO }}.git" fork --depth=1
          Set-Location fork
          git remote add upstream "https://github.com/${{ env.UPSTREAM_REPO }}.git"
          git fetch upstream "${{ env.UPSTREAM_BRANCH }}" --depth=1
          if (git ls-remote --heads origin $branch) { git push origin :$branch }
          git checkout -b $branch "upstream/${{ env.UPSTREAM_BRANCH }}"
          Copy-Item "../${{ steps.manifest.outputs.path }}" "bucket/${{ env.MANIFEST_NAME }}.json" -Force
          git add "bucket/${{ env.MANIFEST_NAME }}.json"
          $commit = "${{ env.MANIFEST_NAME }}: $( if ('${{ steps.upstream.outputs.update }}' -eq 'yes') { 'Update to' } else { 'Add version' } ) $version"
          git commit -m $commit
          git push origin $branch
          $title = "${{ steps.prbody.outputs.title }}"
          $bodyFile = "../${{ steps.prbody.outputs.file }}"
          $out = gh pr create --repo "${{ env.UPSTREAM_REPO }}" --head "${{ github.repository_owner }}:$branch" --base "${{ env.UPSTREAM_BRANCH }}" --title "$title" --body-file "$bodyFile" 2>&1
          if ($LASTEXITCODE -ne 0 -and $out -notmatch 'already exists') {
            Write-Host $out
            exit 1
          }
          Write-Host "PR done."

      - name: Final note (nothing executed)
        if: steps.existing_pr.outputs.pr_exists == 'yes' || (steps.existing_pr.outputs.pr_exists == 'no' && steps.upstream.outputs.skip == 'yes')
        run: echo "Workflow finished early (duplicate PR or already current upstream)."
