name: Sync Main to Develop

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and Rebase Sync Branch
        id: sync_branch
        run: |
          TEMP_BRANCH="sync/main-to-develop-${{ github.run_id }}"
          echo "branch=${TEMP_BRANCH}" >> $GITHUB_OUTPUT
          git checkout -b $TEMP_BRANCH origin/main
          git push origin $TEMP_BRANCH

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          title: "🤖 Sync: Merge main into develop"
          body: "This PR automatically syncs the latest changes from the `main` branch into `develop`."
          base: develop
          branch: ${{ steps.sync_branch.outputs.branch }}
          delete-branch: true

      - name: Enable Auto-Merge (via gh CLI)
        if: steps.create_pr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          PR_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
        run: |
          gh pr merge $PR_NUMBER --auto --rebase
